using System.Collections.Generic;

namespace ComicsLibrary.ViewModels
{
    public class LanguageType
    {
        public string Id { get; set; }
        public string Name { get; set; }

        public static List<LanguageType> FillLanguages()
        {
            var languages = new List<LanguageType>
            {
                new LanguageType { Name = "Abkhazian", Id = "ab" },
                new LanguageType { Name = "Afar", Id = "aa" },
                new LanguageType { Name = "Afrikaans", Id = "af" },
                new LanguageType { Name = "Akan", Id = "ak" },
                new LanguageType { Name = "Albanian", Id = "sq" },
                new LanguageType { Name = "Amharic", Id = "am" },
                new LanguageType { Name = "Arabic", Id = "ar" },
                new LanguageType { Name = "Aragonese", Id = "an" },
                new LanguageType { Name = "Armenian", Id = "hy" },
                new LanguageType { Name = "Assamese", Id = "as" },
                new LanguageType { Name = "Avaric", Id = "av" },
                new LanguageType { Name = "Avestan", Id = "ae" },
                new LanguageType { Name = "Aymara", Id = "ay" },
                new LanguageType { Name = "Azerbaijani", Id = "az" },
                new LanguageType { Name = "Bambara", Id = "bm" },
                new LanguageType { Name = "Bashkir", Id = "ba" },
                new LanguageType { Name = "Basque", Id = "eu" },
                new LanguageType { Name = "Belarusian", Id = "be" },
                new LanguageType { Name = "Bengali", Id = "bn" },
                new LanguageType { Name = "Bihari languages", Id = "bh" },
                new LanguageType { Name = "Bislama", Id = "bi" },
                new LanguageType { Name = "Bosnian", Id = "bs" },
                new LanguageType { Name = "Breton", Id = "br" },
                new LanguageType { Name = "Bulgarian", Id = "bg" },
                new LanguageType { Name = "Burmese", Id = "my" },
                new LanguageType { Name = "Catalan, Valencian", Id = "ca" },
                new LanguageType { Name = "Chamorro", Id = "ch" },
                new LanguageType { Name = "Chechen", Id = "ce" },
                new LanguageType { Name = "Chichewa, Chewa, Nyanja", Id = "ny" },
                new LanguageType { Name = "Chinese", Id = "zh" },
                new LanguageType { Name = "Chuvash", Id = "cv" },
                new LanguageType { Name = "Cornish", Id = "kw" },
                new LanguageType { Name = "Corsican", Id = "co" },
                new LanguageType { Name = "Cree", Id = "cr" },
                new LanguageType { Name = "Croatian", Id = "hr" },
                new LanguageType { Name = "Czech", Id = "cs" },
                new LanguageType { Name = "Danish", Id = "da" },
                new LanguageType { Name = "Divehi, Dhivehi, Maldivian", Id = "dv" },
                new LanguageType { Name = "Dutch, Flemish", Id = "nl" },
                new LanguageType { Name = "Dzongkha", Id = "dz" },
                new LanguageType { Name = "English", Id = "en" },
                new LanguageType { Name = "Esperanto", Id = "eo" },
                new LanguageType { Name = "Estonian", Id = "et" },
                new LanguageType { Name = "Ewe", Id = "ee" },
                new LanguageType { Name = "Faroese", Id = "fo" },
                new LanguageType { Name = "Fijian", Id = "fj" },
                new LanguageType { Name = "Finnish", Id = "fi" },
                new LanguageType { Name = "French", Id = "fr" },
                new LanguageType { Name = "Fulah", Id = "ff" },
                new LanguageType { Name = "Galician", Id = "gl" },
                new LanguageType { Name = "Georgian", Id = "ka" },
                new LanguageType { Name = "German", Id = "de" },
                new LanguageType { Name = "Greek, Modern (1453–)", Id = "el" },
                new LanguageType { Name = "Guarani", Id = "gn" },
                new LanguageType { Name = "Gujarati", Id = "gu" },
                new LanguageType { Name = "Haitian, Haitian Creole", Id = "ht" },
                new LanguageType { Name = "Hausa", Id = "ha" },
                new LanguageType { Name = "Hebrew", Id = "he" },
                new LanguageType { Name = "Herero", Id = "hz" },
                new LanguageType { Name = "Hindi", Id = "hi" },
                new LanguageType { Name = "Hiri Motu", Id = "ho" },
                new LanguageType { Name = "Hungarian", Id = "hu" },
                new LanguageType { Name = "Interlingua (International Auxiliary Language Association)", Id = "ia" },
                new LanguageType { Name = "Indonesian", Id = "id" },
                new LanguageType { Name = "Interlingue, Occidental", Id = "ie" },
                new LanguageType { Name = "Irish", Id = "ga" },
                new LanguageType { Name = "Igbo", Id = "ig" },
                new LanguageType { Name = "Inupiaq", Id = "ik" },
                new LanguageType { Name = "Ido", Id = "io" },
                new LanguageType { Name = "Icelandic", Id = "is" },
                new LanguageType { Name = "Italian", Id = "it" },
                new LanguageType { Name = "Inuktitut", Id = "iu" },
                new LanguageType { Name = "Japanese", Id = "ja" },
                new LanguageType { Name = "Javanese", Id = "jv" },
                new LanguageType { Name = "Kalaallisut, Greenlandic", Id = "kl" },
                new LanguageType { Name = "Kannada", Id = "kn" },
                new LanguageType { Name = "Kanuri", Id = "kr" },
                new LanguageType { Name = "Kashmiri", Id = "ks" },
                new LanguageType { Name = "Kazakh", Id = "kk" },
                new LanguageType { Name = "Central Khmer", Id = "km" },
                new LanguageType { Name = "Kikuyu, Gikuyu", Id = "ki" },
                new LanguageType { Name = "Kinyarwanda", Id = "rw" },
                new LanguageType { Name = "Kirghiz, Kyrgyz", Id = "ky" },
                new LanguageType { Name = "Komi", Id = "kv" },
                new LanguageType { Name = "Kongo", Id = "kg" },
                new LanguageType { Name = "Korean", Id = "ko" },
                new LanguageType { Name = "Kurdish", Id = "ku" },
                new LanguageType { Name = "Kuanyama, Kwanyama", Id = "kj" },
                new LanguageType { Name = "Latin", Id = "la" },
                new LanguageType { Name = "Luxembourgish, Letzeburgesch", Id = "lb" },
                new LanguageType { Name = "Ganda", Id = "lg" },
                new LanguageType { Name = "Limburgan, Limburger, Limburgish", Id = "li" },
                new LanguageType { Name = "Lingala", Id = "ln" },
                new LanguageType { Name = "Lao", Id = "lo" },
                new LanguageType { Name = "Lithuanian", Id = "lt" },
                new LanguageType { Name = "Luba-Katanga", Id = "lu" },
                new LanguageType { Name = "Latvian", Id = "lv" },
                new LanguageType { Name = "Manx", Id = "gv" },
                new LanguageType { Name = "Macedonian", Id = "mk" },
                new LanguageType { Name = "Malagasy", Id = "mg" },
                new LanguageType { Name = "Malay", Id = "ms" },
                new LanguageType { Name = "Malayalam", Id = "ml" },
                new LanguageType { Name = "Maltese", Id = "mt" },
                new LanguageType { Name = "Maori", Id = "mi" },
                new LanguageType { Name = "Marathi", Id = "mr" },
                new LanguageType { Name = "Marshallese", Id = "mh" },
                new LanguageType { Name = "Mongolian", Id = "mn" },
                new LanguageType { Name = "Nauru", Id = "na" },
                new LanguageType { Name = "Navajo, Navaho", Id = "nv" },
                new LanguageType { Name = "North Ndebele", Id = "nd" },
                new LanguageType { Name = "Nepali", Id = "ne" },
                new LanguageType { Name = "Ndonga", Id = "ng" },
                new LanguageType { Name = "Norwegian Bokmål", Id = "nb" },
                new LanguageType { Name = "Norwegian Nynorsk", Id = "nn" },
                new LanguageType { Name = "Norwegian", Id = "no" },
                new LanguageType { Name = "Sichuan Yi, Nuosu", Id = "ii" },
                new LanguageType { Name = "South Ndebele", Id = "nr" },
                new LanguageType { Name = "Occitan", Id = "oc" },
                new LanguageType { Name = "Ojibwa", Id = "oj" },
                new LanguageType { Name = "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", Id = "cu" },
                new LanguageType { Name = "Oromo", Id = "om" },
                new LanguageType { Name = "Oriya", Id = "or" },
                new LanguageType { Name = "Ossetian, Ossetic", Id = "os" },
                new LanguageType { Name = "Punjabi, Panjabi", Id = "pa" },
                new LanguageType { Name = "Pali", Id = "pi" },
                new LanguageType { Name = "Persian", Id = "fa" },
                new LanguageType { Name = "Polish", Id = "pl" },
                new LanguageType { Name = "Pashto, Pushto", Id = "ps" },
                new LanguageType { Name = "Portuguese", Id = "pt" },
                new LanguageType { Name = "Quechua", Id = "qu" },
                new LanguageType { Name = "Romansh", Id = "rm" },
                new LanguageType { Name = "Rundi", Id = "rn" },
                new LanguageType { Name = "Romanian, Moldavian, Moldovan", Id = "ro" },
                new LanguageType { Name = "Russian", Id = "ru" },
                new LanguageType { Name = "Sanskrit", Id = "sa" },
                new LanguageType { Name = "Sardinian", Id = "sc" },
                new LanguageType { Name = "Sindhi", Id = "sd" },
                new LanguageType { Name = "Northern Sami", Id = "se" },
                new LanguageType { Name = "Samoan", Id = "sm" },
                new LanguageType { Name = "Sango", Id = "sg" },
                new LanguageType { Name = "Serbian", Id = "sr" },
                new LanguageType { Name = "Gaelic, Scottish Gaelic", Id = "gd" },
                new LanguageType { Name = "Shona", Id = "sn" },
                new LanguageType { Name = "Sinhala, Sinhalese", Id = "si" },
                new LanguageType { Name = "Slovak", Id = "sk" },
                new LanguageType { Name = "Slovenian", Id = "sl" },
                new LanguageType { Name = "Somali", Id = "so" },
                new LanguageType { Name = "Southern Sotho", Id = "st" },
                new LanguageType { Name = "Spanish, Castilian", Id = "es" },
                new LanguageType { Name = "Sundanese", Id = "su" },
                new LanguageType { Name = "Swahili", Id = "sw" },
                new LanguageType { Name = "Swati", Id = "ss" },
                new LanguageType { Name = "Swedish", Id = "sv" },
                new LanguageType { Name = "Tamil", Id = "ta" },
                new LanguageType { Name = "Telugu", Id = "te" },
                new LanguageType { Name = "Tajik", Id = "tg" },
                new LanguageType { Name = "Thai", Id = "th" },
                new LanguageType { Name = "Tigrinya", Id = "ti" },
                new LanguageType { Name = "Tibetan", Id = "bo" },
                new LanguageType { Name = "Turkmen", Id = "tk" },
                new LanguageType { Name = "Tagalog", Id = "tl" },
                new LanguageType { Name = "Tswana", Id = "tn" },
                new LanguageType { Name = "Tonga (Tonga Islands)", Id = "to" },
                new LanguageType { Name = "Turkish", Id = "tr" },
                new LanguageType { Name = "Tsonga", Id = "ts" },
                new LanguageType { Name = "Tatar", Id = "tt" },
                new LanguageType { Name = "Twi", Id = "tw" },
                new LanguageType { Name = "Tahitian", Id = "ty" },
                new LanguageType { Name = "Uighur, Uyghur", Id = "ug" },
                new LanguageType { Name = "Ukrainian", Id = "uk" },
                new LanguageType { Name = "Urdu", Id = "ur" },
                new LanguageType { Name = "Uzbek", Id = "uz" },
                new LanguageType { Name = "Venda", Id = "ve" },
                new LanguageType { Name = "Vietnamese", Id = "vi" },
                new LanguageType { Name = "Volapük", Id = "vo" },
                new LanguageType { Name = "Walloon", Id = "wa" },
                new LanguageType { Name = "Welsh", Id = "cy" },
                new LanguageType { Name = "Wolof", Id = "wo" },
                new LanguageType { Name = "Western Frisian", Id = "fy" },
                new LanguageType { Name = "Xhosa", Id = "xh" },
                new LanguageType { Name = "Yiddish", Id = "yi" },
                new LanguageType { Name = "Yoruba", Id = "yo" },
                new LanguageType { Name = "Zhuang, Chuang", Id = "za" },
                new LanguageType { Name = "Zulu", Id = "zu" }
            };

            return languages;
        }
    }
}